org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=mysteriacraft
mod_name=MysteriaCraft
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.mysteriacraft
mod_authors=dpoillon89
mod_description=Mod Minecraft magique pour MysteriaCraft
